const Groq = require('groq-sdk');

// Note: Initialize Groq client using process.env.GROQ_API_KEY
// const groq = new Groq({ apiKey: process.env.GROQ_API_KEY });

/**
 * Sends a text prompt to a Groq-hosted AI model and returns the completed text response.
 *
 * @function getCompletion
 * @async
 * @param {string} prompt - The text prompt containing instructions or context to be sent to the AI.
 * @param {Object} [options={}] - Optional configuration options (e.g., temperature, maxTokens).
 * @param {number} [options.temperature] - Controls the randomness of the model's output.
 * @param {number} [options.maxTokens] - The maximum number of tokens to generate in the completion.
 * @returns {Promise<string>} The raw text response generated by the Groq AI model.
 *
 * Implementation Steps:
 * 1. Verify that process.env.GROQ_API_KEY is defined; if not, throw an appropriate configuration error.
 * 2. Instantiate or retrieve the initialized Groq client using the API key.
 * 3. Call the groq.chat.completions.create method using a fast Groq model (e.g. 'llama3-8b-8192').
 * 4. Pass the user prompt formatted inside the messages array, along with optional temperature or token limits.
 * 5. Extract the generated response string from choice content (i.e. response.choices[0]?.message?.content).
 * 6. Return the string or throw/handle errors cleanly if the API request fails.
 */
async function getCompletion(prompt, options = {}) {
  return "Mock AI response: This is a placeholder summary/response from Groq AI client."; // TODO: implement
}

module.exports = {
  getCompletion
};
